### ISSUE TITLE
IndexOutOfBounds when changing colormap in FractalExplorer

### ISSUE THREAD

**Issue by barrybecker4** [bb4/bb4-simulations#13]
Exception in thread "Thread-18" java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at com.barrybecker4.ui.util.ColorMap.getColorForValue(ColorMap.java:60)
    at com.barrybecker4.simulation.common.rendering.ModelImage.updateImage(ModelImage.java:72)
    at com.barrybecker4.simulation.fractalexplorer.FractalExplorer.timeStep(FractalExplorer.java:119)
    at com.barrybecker4.ui.animation.AnimationComponent.run(AnimationComponent.java:91)
    at java.lang.Thread.run(Unknown Source)

**Comment by barrybecker4** [comment]
I have not seen it lately

**Comment by barrybecker4** [comment]
Just got it in CaveExplorer too when adding a control point
{code}
ARGS = -panel_class, com.barrybecker4.simulation.cave.CaveExplorer
Exception in thread "Thread-1" java.lang.ArrayIndexOutOfBoundsException: 6
	at com.barrybecker4.ui.util.ColorMap.interpolate(ColorMap.scala:75)
	at com.barrybecker4.ui.util.ColorMap.getColorForValue(ColorMap.scala:51)
	at com.barrybecker4.simulation.cave.rendering.CaveRenderer.$anonfun$render$2(CaveRenderer.scala:46)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:156)
	at com.barrybecker4.simulation.cave.rendering.CaveRenderer.$anonfun$render$1(CaveRenderer.scala:42)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:156)
	at com.barrybecker4.simulation.cave.rendering.CaveRenderer.render(CaveRenderer.scala:41)
	at com.barrybecker4.simulation.cave.model.CaveModel.doRender(CaveModel.scala:182)
	at com.barrybecker4.simulation.cave.model.CaveModel.$anonfun$timeStep$1(CaveModel.scala:174)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:156)
	at com.barrybecker4.simulation.cave.model.CaveModel.timeStep(CaveModel.scala:171)
	at com.barrybecker4.simulation.cave.CaveExplorer.timeStep(CaveExplorer.scala:52)
	at com.barrybecker4.ui.animation.AnimationComponent.run(AnimationComponent.scala:58)
	at java.lang.Thread.run(Thread.java:745)
{code}

**Comment by barrybecker4** [comment]
Fixed in bb4-ui library. Also added ttip instructions or how to add/remove markers.
