### ISSUE TITLE
WFC: NPE for Flowers model

### ISSUE THREAD

**Issue by barrybecker4** [bb4/bb4-simulations#25]
I often get a stack trace like this
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.barrybecker4.simulation.waveFunctionCollapse.model.wave.Wave.doPropagation(Wave.scala:147)
	at com.barrybecker4.simulation.waveFunctionCollapse.model.wave.Wave.propagate(Wave.scala:139)
	at com.barrybecker4.simulation.waveFunctionCollapse.model.WfcModel.$anonfun$advance$2(WfcModel.scala:65)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:190)
	at com.barrybecker4.simulation.waveFunctionCollapse.model.WfcModel.advance(WfcModel.scala:59)
	at com.barrybecker4.simulation.waveFunctionCollapse.model.WfcModel.runWithLimit(WfcModel.scala:43)
	at com.barrybecker4.simulation.waveFunctionCollapse.model.WfcModel.startRun(WfcModel.scala:49)
	at com.barrybecker4.simulation.waveFunctionCollapse.DynamicOptions.runModel(DynamicOptions.scala:248)
	at com.barrybecker4.simulation.waveFunctionCollapse.DynamicOptions.itemStateChanged(DynamicOptions.scala:261)
	at java.desktop/javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1227)
	at java.desktop/javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1279)
```

**Comment by barrybecker4** [comment]
Fixed. This was due to a concurrency issue.
